apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: raftstorageclasses.storage.cloud.atomix.io
spec:
  group: storage.cloud.atomix.io
  names:
    kind: RaftStorageClass
    listKind: RaftStorageClassList
    plural: raftstorageclasses
    singular: raftstorageclass
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                imagePullPolicy:
                  type: string
                replicas:
                  type: integer


