apiVersion: storage.cloud.atomix.io/v1beta1
kind: RaftStorageClass
metadata:
  name: raft-database
  labels:
    app: raft-database
spec:
  image: atomix/raft-storage-node:v0.1.0
  imagePullPolicy: IfNotPresent
  replicas: 1
  partitionsPerCluster: 3
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 1Gi
---
apiVersion: cloud.atomix.io/v1beta3
kind: Database
metadata:
  name: raft-database
spec:
  partitions: 1
  storageClass:
    group: storage.cloud.atomix.io
    version: v1beta1
    kind: RaftStorageClass
    name: raft-database
    namespace: default
